name: Deployment

on:
  push:
    branches: [main, ci*]
  workflow_dispatch:

jobs:
  run:
    name: Deploy
    env:
      CI: true
      DISCORD_BOT_ID: ${{ secrets.DISCORD_BOT_ID }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      NODE_ENV: production
      PROD_ERROR_EMAIL: ${{ secrets.PROD_ERROR_EMAIL }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: pm2 delete svbot || true
      - run: pm2 start out/main.js --name "svbot"
