name: Deployment

on:
  push:
    branches: [main, ci*]
  workflow_dispatch:

jobs:
  run:
    name: Deploy
    env:
      CI: true
      NODE_ENV: production
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      PROD_ERROR_EMAIL: ${{ secrets.PROD_ERROR_EMAIL }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.tool-versions'
      #     check-latest: true
      #     cache: 'yarn'
      - run: corepack enable
      - run: yarn install
      - run: yarn build
      - run: pm2 delete svbot || true
      - run: pm2 start out/main.js --name "svbot"
