name: Deployment

on:
  push:
    branches: [main]

jobs:
  run:
    env:
      CI: true
      NODE_ENV: production
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          check-latest: true
      - run: yarn install
      - run: yarn build
      - run: pm2 delete svbot || true
      - run: pm2 start out/main.js --name "svbot"
